import { Router, type IRouter } from "express";
import healthRouter from "./health";
import gameRouter from "./game";
import squadRouter from "./squad";
import tacticsRouter from "./tactics";
import fixturesRouter from "./fixtures";
import leagueRouter from "./league";
import transfersRouter from "./transfers";
import inboxRouter from "./inbox";
import financesRouter from "./finances";
import trainingRouter from "./training";
import injuriesRouter from "./injuries";
import scoutingRouter from "./scouting";
import contractsRouter from "./contracts";
import setPiecesRouter from "./setpieces";
import staffRouter from "./staff";
import pressconfRouter from "./pressconf";
import matchdayRouter from "./matchday";

const router: IRouter = Router();

router.use(healthRouter);
router.use(gameRouter);
router.use(squadRouter);
router.use(tacticsRouter);
router.use(fixturesRouter);
router.use(leagueRouter);
router.use(transfersRouter);
router.use(inboxRouter);
router.use(financesRouter);
router.use(trainingRouter);
router.use(injuriesRouter);
router.use(scoutingRouter);
router.use(contractsRouter);
router.use(setPiecesRouter);
router.use(staffRouter);
router.use(pressconfRouter);
router.use(matchdayRouter);

export default router;
